NUM_GPUS: 4
RNG_SEED: 0
TRAIN:
  ENABLE: True
  MAX_EPOCH: 40
  AUTO_RESUME: True
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_PATH: ""
  CHECKPOINT_EPOCH_RESET: False
  AMP_ENABLE: True
TEST:
  ENABLE: False
  CHECKPOINT_PATH: ''
  THRES: 0.5
MODEL:
  FIND_UNUSED_PARAMETERS: False
DATASET:
  DATASET_NAME: Default_dataset
  ROOT_DIR: /path/to/your/dataset
  TRAIN_AUGMENTATIONS:
    Resize:
      height: 380
      width: 380
    OneOf:
      GaussianBlur:
        # blur_limit: [3,7]
        sigma_limit: 0.7
    ImageCompression:
      quality_lower: 65
      quality_upper: 80
    RandomResizedCrop:
      height: 380
      width: 380
      scale: [0.8, 1]
      ratio: [0.75, 1.33]
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  TEST_AUGMENTATIONS:
    Resize:
      height: 380
      width: 380
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
DATALOADER:
  BATCH_SIZE: 16
  NUM_WORKERS: 8
  PIN_MEM: True
LOSS:
  LAMBDA_CLS: 0.25
  LAMBDA_SEG: 1.0
  DETECTION_LOSS:
    NAME: BCELossWithLogits
  LOCALIZATION_LOSS:
    NAME: DiceLoss
OPTIMIZER:
  OPTIMIZER_METHOD: adamw
  BASE_LR: 0.001
  ADAM_BETAS: [0.9, 0.999]
  EPS: 0.00000001
  WEIGHT_DECAY: 0.01
  AMSGRAD: False
SCHEDULER:
  LR_NOISE_PCT: 0.67
  LR_NOISE_STD: 1.0
  SEED: 42
  LR_CYCLE_MUL: 1.0
  LR_CYCLE_DECAY: 0.1
  LR_CYCLE_LIMIT: 1
  SCHEDULER_TYPE: cosine
  MIN_LR: 0.000001
  WARMUP_LR: 0
  WARMUP_EPOCHS: 0
  COOLDOWN_EPOCHS: 10
  LR_K_DECAY: 1.0
  SCHEDULER_STEP: 5
  SCHEDULER_GAMMA: 0.5
OUTPUT_DIR: 'default'